context/amf_ue.go, gmm/handler.go, gmm/message/send.go
Amf crashed during registration when it triggers after nw intiated deregister
issue due to stale ue context present during registration, However
registration should pass and amf should do context replacement.
AMF is not clearing Subscribed Nssai List during registration, so it
to use older subscribed nssai which leads to crash in AMF.
=> AMF Crash Fix:

go.sum
This PR holds changes to fix the following error which was occurring while building AMF,
```
verifying github.com/omec-project/nas@v1.1.1/go.mod: checksum mismatch
downloaded: h1:gXqi/IZwEGXno26X8wg8ITsAUiemRQ7PkIJOWP1NzGA=
go.sum:     h1:WRl/gOe8pZATzTk5pHbAcqUuWbmLdVV/jzjnl5lCcJ8=
SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
For more information, see 'go help module-auth'
```
=> fix: Update commit hash for nas package

gmm/mock_gmm.go, oam/api_purge_ue_context.go, oam/routers.go, producer/oam.go, producer/oam_test.go
This PR implements a REST API for purging the UE context. If the UE is in registered state, Network Initiated deregistration is triggered. Else, UE is directly removed. PFA for logs.
[amf.txt](https://github.com/omec-project/amf/files/8915724/amf.txt)
[gnbsim.txt](https://github.com/omec-project/amf/files/8915728/gnbsim.txt)
=> REST API_PURGE UE CONTEXT

ngap/service/service.go
Keeping it just 8k causes lot of message drop at the socket level.
=> Fix readbuffer size in AMF.

service/init.go
This PR fixes an issue introduced in commit https://github.com/omec-project/amf/commit/3b7558f03d8388b4aac65f27a1d26f93e58e9de7 where the `UpdateConfig` would return early instead of continuously looking for new messages in the channel.
Fixes #134
=> fix: Removes stop of UpdateConfig channel loop when 1 item has no network slice

consumer/sm_context.go
This PR makes it so that  the `SelectSmf` function retrieves `SearchNssfNSSelectionInstance` even if there already is a stored value for the NSSF URI. This fixes an issue where the NSSF uri was only stored once on AMF startup and never retrieved again. This was a problem in cases where the NSSF crashed and its IP changed.
Fixes #133
=> fix: fetches nssf uri even if already cached

.golangci.yml, consumer/am_policy.go, consumer/communication.go, consumer/nf_mangement.go, consumer/sm_context.go, consumer/subscriber_data_management.go, consumer/ue_authentication.go
Re-enables the `nakedret` linter and fix the issues found by it. This PR only makes the current implicit behaviour explicit to satisfy the linter. It does not change any current behaviors.
=> fix: Reenable nakedret linter and fix found issues

consumer/subscriber_data_management.go, gmm/handler.go
Because the AMF is keeping a cache of all the UEs it sees and saves the NFs URI in it, when the UDM is restarted with a new IP for any reason, the first connection by a previously seen user would get rejected.
It is easy to test the previous error by deploying the core and gnbsim, configuring a subscriber and executing a succesful simulation. After that, deleting the UDM pod in Kubernetes and wait for the pod to be restarted properly. Run a new simulation, and it will fail. Running the simulation again after a failure will work, because it will have cleaned the cache.
This change makes it so that we always ask the NRF for the URI to use.
=> Fix NudmSDM url after udm crash

.gitignore, .golangci.yml, amf_test.go, consumer/sm_context.go, context/amf_ran.go, context/amf_ue.go, context/context.go, context/ran_ue.go, gmm/handler.go, gmm/sm.go, metrics/kafka.go, metrics/telemetry.go, nas/handler.go, ngap/dispatcher.go, ngap/handler.go, producer/oam.go, producer/oam_test.go, service/amf_server.go, service/init.go
Enables the `errcheck` linter and add error checking where missing, simply logging the error.
Also remove the `deadcode` and `varcheck` linters as they are abandoned by their upstream.
=> chore: Re-enable errcheck linter with required fixes

.golangci.yml, consumer/nf_discovery.go, consumer/sm_context.go, context/amf_ue.go, context/ran_ue.go, context/sm_context.go, gmm/handler.go, gmm/message/send.go, metrics/kafka.go, ngap/handler.go, ngap/message/send.go, ngap/ngap_test.go, producer/callback.go, producer/n1n2message.go, service/init.go
Enables the `govet` linter and fix reported errors.
=> chore: Enable govet linter and fix reported errors

.golangci.yml, consumer/sm_context.go, gmm/message/build.go, metrics/kafka.go, producer/oam_test.go, service/init.go, util/init_context.go
Enables the `unused` linter and remove unused code reported. Tested with a gnbsim simulation.
=> chore: Enable 'unused' linter and fix reported problems

.golangci.yml, consumer/sm_context.go, gmm/handler.go, service/init.go
Enable goconst linter and fix reported issues. Tested with a gnbsim simulation.
=> chore: Enable goconst linter and fix reported issues

.golangci.yml, context/context.go, context/db.go, gmm/handler.go, nas/handler.go, ngap/handler.go
Enables the `unconvert` linter and fix reported issues. This simply removes redundant conversion.
Also removes the `maligned` linter that is deprecated.
=> chore: Enable unconvert linter and fix reported issues

context/amf_ue.go, context/context.go, context/db.go, go.mod, go.sum
Changes the import path of the `idgenerator` module to use the `util` project. Tested with a successful simulation with gnbsim.
=> chore: Move idgenerator dep to util project

communication/api_individual_subscription_document.go, communication/api_individual_ue_context_document.go, communication/api_n1_n2_individual_subscription_document.go, communication/api_n1_n2_message_collection_document.go, communication/api_n1_n2_subscriptions_collection_for_individual_ue_contexts_document.go, communication/api_subscriptions_collection_document.go, eventexposure/api_individual_subscription_document.go, eventexposure/api_subscriptions_collection_document.go, go.mod, go.sum, httpcallback/api_am_policy_control_update_notify.go, httpcallback/api_n1_message_notify.go, httpcallback/api_nf_subscribe_notify.go, httpcallback/api_sm_context_status_notify.go, location/api_individual_ue_context_document.go, mt/api_ue_context_document.go, oam/api_purge_ue_context.go, oam/api_registered_ue_context.go, producer/callback.go, producer/event_exposure.go, producer/location_info.go, producer/mt.go, producer/n1n2message.go, producer/oam.go, producer/subscription.go, producer/ue_context.go
Moves the `http_wrapper` dependency to the `util` project. Tested with a successful `gnbsim` simulation.
=> chore: Move http_wrapper dependency to util project

.github/workflows/docker.yml, .github/workflows/stale.yml
Add two GitHub Actions:
- Docker push to push Docker images to Aether registry
- Stale to mark issues/PRs as stale after a month of inactivity
=> Add docker push and stale Actions

amfTest/amfcfg.yaml, amfTest/amfcfg_with_custom_webui_url.yaml, factory/amf_config_test.go
Adding unit test to validate that custom Webui URL is successfully set.
=> chore: Adding unit tests for custom Webui URL

service/init.go
This PR fixes the wrong behaviour for which the AMF tries to create collections mongoDB even when the `EnableDbStore` configuration option is set to false.
=> fix: create collections only when database is enabled

amfTest/amfcfg.yaml, context/context.go, factory/config.go, service/init.go, util/init_context.go
This PR enables to set custom paths for TLS certificate and private key.
This PR adds a `tls` container, composed of `pem` and `key` keys, inside `sbi` container to specify the paths of TLS certificate and private key to use for the HTTPS server.
=> feat: parametrize paths for TLS certificate and private key

amf_test.go, consumer/nf_discovery.go, gmm/handler.go, go.mod, go.sum, ngap/handler.go, producer/callback.go, producer/oam.go, service/init.go
This PR reduces the decrease the complexity of dependencies by using nrfcahce library from Openapi.
fix: Sove linting issues in the repository
=> chore: Use nrfcache from openapi repository

ngap/handler.go
Issue: We have successfully connected the SD core with the OAI-gNB (usrp B210) and real UE. However, the pod crashes consistently when we disable and re-enable mobile data.
Troubleshoot: We identified the root cause of the pod crash: the Pdusessionresourcesetupresponse message contains both PDUSessionResourceSetupListSures and PDUSessionResourceFailedToSetupListSures IE's. While PDUSessionResourceSetupListSures contains the expected pduSessionId matching the one sent in the PDUSessionResourceSetupRequest, PDUSessionResourceFailedToSetupListSures contains a pduSessionId of 0, causing the pod to crash because the corresponding SmContext cannot be found.
Fix: Added continue if SmContext is not found.
=> AMF pod crash when Mobile data disabled and re-enabled in UE

consumer/sm_context.go
Issue:
Xn Handover failure due to AMF crashing when the gNodeB provides an incorrect PDU Session ID in the NG Path Switch Request.
Troubleshoot:
The crash was traced to the absence of a proper check for the PDU Session ID in the SendUpdateSmContextXnHandover function, causing the AMF to crash when receiving an incorrect or invalid PDU Session ID from the gNodeB.
Fix:
The issue has been resolved by adding a nil check in the SendUpdateSmContextXnHandover function.
Supporting Data:
[Xn-Handover-AMF-Crash-PCAP-Logs.zip](https://github.com/user-attachments/files/17095452/Xn-Handover-AMF-Crash-PCAP-Logs.zip)
=> Xn Handover - AMF crash fix

context/ran_ue.go, factory/config.go, factory/factory.go, gmm/message/send.go, ngap/handler.go, service/init.go
1. UE Context Release handling leads to total 3 messages. Final message is UE Context Release Complete is sent by gNB. Service request was reaching AMF before UE Context Release Complete and this leads to crash, since UE to RAN-UE linking gets removed while processing Complete message. Added necessary protection to fix the crash
2. Other fixes involve AMF should not handle the new calls if it has not yet received any config else AMF crashes due to no config
=> Number of fixes in AMF to handle multiple service req

gmm/handler.go
Issue:
Authentication failure due to duplicate ngKSI values
Troubleshoot:
Troubleshooting revealed that the Core includes the same ngKSI value from Registration Request in Authentication Request.
Fix:
Updated ngKSI value after 5G AKA procedure.
Original PR - https://github.com/omec-project/amf/pull/307  closed due to local repo issues and current new PR is opened after addressing comments.
=> ngKSI already in use - Bug Fix

producer/ue_context.go
Aims to fix https://github.com/canonical/sdcore-amf-k8s-operator/issues/472
Invalid memory address or nil pointer dereference error occurs when producer.HandleRegistrationStatusUpdateRequest is called
(producer/ue_context.go:599).  This PR first checks if a message is read through the channel before proceeding with response data and problem details.
=> fix: check if a message read from channel to prevent nil pointer dereference

gmm/sm.go, producer/ue_context.go
Aiming to fix any potential issue that causes: https://github.com/canonical/sdcore-amf-k8s-operator/issues/472
I am not able to reproduce the problem. But, this PR aiming to fix potential issues in the `HandleRegistrationStatusUpdateRequest` and `ContextSetup` functions.
- Safely Handle Type Assertions
- Handle unexpected response data types
- Check if  message retrieved from channel and handle if no message retrieved situation
- Check the message format and handle wrong message format
=> fix: potential problems that may cause a panic during context setup

ngap/handler.go
AMF sent Initial Context Setup message to gNB, but before gNB initiated context release while context setup was in-progress. This leads to PDU session release and later when Initial Context Setup failure is received from the gNodeB, amf failed to find pdu-session.
its wise to just process initial context setup failure message at AMF & skip processing which sends message towards SMF.
=> Fix AMF crash

gmm/sm.go
Issue:
When an abnormal UE exit occurs, the core network state remains unchanged, preventing subsequent UE registrations and sometimes leads to AMF pod crash.
Fix:
Invoked SendEvent() to move to deregistered state in case of a state mismatch.
Applied the fix to all scenarios where a state mismatch occurs.
Supporting Data:
[amfcrash (3).zip](https://github.com/user-attachments/files/18868364/amfcrash.3.zip)
=> UE connection fails due to state mismatch issue

.github/workflows/main.yml
Run E2E tests for pull requests as part of CI process. Hence, we make sure that integrations tests will pass without manual testing.
=> chore: run E2E tests automatically

service/amf_server.go, service/init.go
This PR fixes the shutdown of the tracer introduced in #473.
When an interrupt or SIGTERM are provided, deferred functions are not called.
This PR moves the shutdown of the tracer in the `Terminate` function, so that it can be properly handled.
=> fix: properly shutdown tracer

context/amf_ran.go, context/context.go, gmm/handler.go
If `SupportDnnLists` is not set in the configuration file, there is a potential panic in the code.
If the UE's subscription obtained from the UDM does not contain the default DNN, the AMF willl try to get it from the `ue.SmfSelectionData`. If not found, the AMF will get the DNN from `SupportDnnLists`. If `SupportDnnLists` is empty, it will fallback to "internet" as done in [producer/callback.go](https://github.com/omec-project/amf/blob/d8dd0d93707be1f3b81f0ddf6e9eba941e15dec3/producer/callback.go#L155C7-L155C15)
=> fix: remove potential panic in SupportDnnLists
